### ISSUE TITLE
Integer HSL values should probably be explicitly floats

### ISSUE THREAD

**Issue by Flopgop** [catppuccin/palette#117]
I noticed this after it broke my handwritten parser.
Some JSON parsers in some languages (in my case Odin, where it is part of the stdlib) require floating point values to be explicitly floats to actually be parsed as a float. This breaks my implementation because I loop through every value in the colors object and automatically assume all 3 components of the hue object are floats, which causes a panic because it expected a float not an integer.
https://github.com/catppuccin/palette/blob/b85d36adec22631684ae64ced0a5cdd15462de3b/palette.json#L35

**Comment by Flopgop** [comment]
This also appears to occur in other non-zero integer HSL values across the file

**Comment by MatthiasPortzel** [comment]
This report is a little confusing because JSON doesn’t make a distinction between floats and integers—since it’s JavaScript based it just has one “Number” type. This does make parsing JSON into languages with a float/integer distinction annoying.

It means that these languages and parsers have to support a way to specify whether the user wants Numbers to be parsed as floats or integers. For example, it looks like Odin has a `parse_integers` option which can be set to false to force all numbers to be floats. Some other languages have the ability to tell the JSON parser what ‘schema’ they expect the document to conform to when parsing.

I think it still might make sense for Catppuccin to change to 0.0 if that leads to a better default, but I wanted to add some additional context.

**Comment by backwardspy** [comment]
the palette JSON is generated from typescript [using `JSON.stringify`](https://github.com/catppuccin/palette/blob/main/scripts/gen_palette.ts#L388). as matthias rightly points out, JSON has a single numeric type and so `0` and `0.0` are equal. `JSON.stringify` opts to always format zero as `0`, and so that is what appears in `palette.json`

while we might be able to change this by perhaps using another library or even another language that supports formatting numbers differently, what we're generating now is correct per the JSON spec and so i would instead recommend looking into a solution for your parser such as the option matthias provided above. i don't know odin specifically, but in all other languages i've used there are ways to specify the data you expect the parser to give you.
